from core.orchestrator import Orchestrator
import os

if __name__ == "__main__":
    # Chemin vers le code à refactorer
    input_file = os.path.join("examples", "bad_code.py")
    output_file = os.path.join("examples", "refactored_code.py")

    # Lire le code existant
    with open(input_file, "r", encoding="utf-8") as f:
        code = f.read()

    orchestrator = Orchestrator()
    results = orchestrator.run(code)

    # Créer un fichier refactoré avec les propositions des agents
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# ===== Refactored Code (Generated by Agentic AI) =====\n\n")
        for agent, data in results.items():
            f.write(f"# --- {agent} ---\n")
            f.write("# Original Analysis:\n")
            for line in data["Analysis"]:
                f.write(f"# {line}\n")
            f.write("\n# LLM Proposal:\n")
            f.write(data["LLM Proposal"])
            f.write("\n\n")

    # Afficher le rapport à la console
    print("===== AGENTIC IA REFACTORING REPORT =====")
    for agent, data in results.items():
        print(f"\n[{agent}]")
        print("Analysis:", data["Analysis"])
        print("LLM Proposal:", data["LLM Proposal"])
        print("-" * 50)

    print(f"\nRefactored code saved to {output_file}")
